name: napari-dinosim
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  # Core scientific stack from conda-forge
  - napari
  - numpy>=1.21.0
  - magicgui>=0.5.0
  - qtpy
  - pillow>=9.0.0
  - matplotlib>=3.5.0
  - tqdm>=4.62.0
  - pytorch
  - torchvision
  - pip:
    - opencv-python
    # Install the plugin itself via pip
    - -e .
